### ISSUE TITLE
'listings': warnings about incompatible versions in the classpath after running any of the scripts in IntelliJ Idea

### ISSUE THREAD

**Issue by Nigel-727** [petersommerhoff/kotlin-for-android-app-development#1]
With some backgound in Java, I am trying to get familiar with Kotlin using the code in the repo.
As a newcomer in anything related to Gradle, for hours now I have been running into an issue when running any of the .kts files in 'listing': even though they run as they should :), at the end of every Run tool window there is always this bunch of lines in red:

```
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/Latitude E7440/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.71/5470d1f752cd342edb77e1062bac07e838d2cea4/kotlin-stdlib-jdk8-1.2.71.jar (version 1.2)
    C:/Users/Latitude E7440/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.2.71/d5439926359caa899f41e1915b19d6d23e49750b/kotlin-script-runtime-1.2.71.jar (version 1.2)
    C:/Users/Latitude E7440/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.71/4ce93f539e2133f172f1167291a911f83400a5d0/kotlin-stdlib-jdk7-1.2.71.jar (version 1.2)
 C:/Users/Latitude E7440/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.71/d9717625bb3c731561251f8dd2c67a1011d6764c/kotlin-stdlib-1.2.71.jar (version 1.2)
    C:/Users/Latitude E7440/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.2.71/ba18ca1aa0e40eb6f1865b324af2f4cbb691c1ec/kotlin-stdlib-common-1.2.71.jar (version 1.2)
    C:/Users/Latitude E7440/.IdeaIC2018.3/config/plugins/Kotlin/kotlinc/lib/kotlin-stdlib.jar (version 1.3)
    C:/Users/Latitude E7440/.IdeaIC2018.3/config/plugins/Kotlin/kotlinc/lib/kotlin-script-runtime.jar (version 1.3)
    C:/Users/Latitude E7440/.IdeaIC2018.3/config/plugins/Kotlin/kotlinc/lib/kotlin-reflect.jar (version 1.3)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

Some background info: I am using IntelliJ Idea Community 2018.3 with 1.3.10 as the default Kotlin plugin version. 
OK, I realize that the version number in last three rows is 1.3, as opposed to the 1.2s above, but... 
Should I actually remove something from the classpath? If so, what is the customary way?

**Comment by petersommerhoff** [comment]
As you mentioned, the problem is that IntelliJ bundles the newer Kotlin 1.3 but we want to use Kotlin 1.2 for the book listing because that's their target version. There are two solutions I see here:

1) Ignore the warnings
2) Or manually downgrade Kotlin to 1.2.71 in IntelliJ for the purposes of following the book. To do so, grab the correct Kotlin plugin download from http://plugins.jetbrains.com/plugin/6954-kotlin -- make sure to choose one with "IJ" suffix for IntelliJ (the "Studio" suffix is for Android Studio). You can uninstall the current Kotlin plugin and install the new one from the Plugins section in the settings. Click "Install plugin from disk..." to install version 1.2.71.
